from pathlib import Path
import platform
import shutil
from typing import Literal

# NUOVA ORGANIZZAZIONE

# PER ORA CONSIDERO DATA_PROCESSING_RAW_DIR COME INPUT E OPEN3D COME OUTPUT

BASE_DIR = Path(__file__).resolve().parent
IS_WINDOWS = platform.system() == "Windows"
if IS_WINDOWS: EXE = '.exe' 
else: EXE = '' 

# ENGINES DIR

ENGINES_DIR = BASE_DIR / 'engines'

ENGINES_COLMAP_DIR = ENGINES_DIR / 'colmap'
if IS_WINDOWS: ENGINES_COLMAP_EXE = ENGINES_COLMAP_DIR / 'bin' / f'colmap{EXE}'
else: 
    SYSTEM_COLMAP = Path(shutil.which("colmap"))
    if SYSTEM_COLMAP:
        ENGINES_COLMAP_EXE = SYSTEM_COLMAP
    else:
        print('Colmap linux installation not found, alternative path loded.')
        ENGINES_COLMAP_EXE = ENGINES_COLMAP_DIR / 'bin' / 'colmap'

ENGINES_OPENMVS_DIR = ENGINES_DIR / 'openmvs'
ENGINES_OPENMVS_INTERFACE_EXE = ENGINES_OPENMVS_DIR / f'InterfaceCOLMAP{EXE}'
ENGINES_OPENMVS_DENSE_EXE = ENGINES_OPENMVS_DIR / f'DensifyPointCloud{EXE}'
ENGINES_OPENMVS_RECONSTRUCT_MESH_EXE = ENGINES_OPENMVS_DIR / f'ReconstructMesh{EXE}'
ENGINES_OPENMVS_REFINE_MESH_EXE = ENGINES_OPENMVS_DIR / f'RefineMesh{EXE}'
ENGINES_OPENMVS_TEXTURE_MESH_EXE = ENGINES_OPENMVS_DIR / f'TextureMesh{EXE}'

# SRC ORGANIZATION

SRC_DIR = BASE_DIR / 'src'

SRC_PROCESSING_DIR = SRC_DIR / 'processing'
SRC_COLMAP_DIR = SRC_DIR / 'colmap'
SRC_OPENMVS_DIR = SRC_DIR / 'openmvs'
SRC_OPEN3D_DIR = SRC_DIR / 'open3d'

SRC_MODELS_DIR = SRC_DIR / 'models'
SRC_UTILS_DIR = SRC_DIR / 'utils'
SRC_CORE_DIR = SRC_DIR / 'core'

# DATA ORGANIZATION

DATA_DIR = BASE_DIR / 'data'

DATA_PROCESSING_DIR = DATA_DIR / 'processing'
DATA_PROCESSING_VIDEO_DIR = DATA_PROCESSING_DIR / 'video'
DATA_PROCESSING_VIDEO_PATH = DATA_PROCESSING_VIDEO_DIR / 'video.MP4'
DATA_PROCESSING_RAW_DIR = DATA_PROCESSING_DIR / 'raw'
DATA_PROCESSING_INTERIM_DIR = DATA_PROCESSING_DIR / 'interim'
DATA_PROCESSING_PROCESSED_DIR = DATA_PROCESSING_DIR / 'processed'

DATA_COLMAP_DIR = DATA_DIR / 'colmap'
DATA_COLMAP_DEFAULT_CAMERAS_DATABASE = DATA_COLMAP_DIR / 'cameras_data.db'
DATA_COLMAP_DEFAULT_GPS_DATA = DATA_COLMAP_DIR / 'gps_data.txt'
DATA_COLMAP_SPARSE_DIR = DATA_COLMAP_DIR / 'sparse'
DATA_COLMAP_ALIGNED_DIR = DATA_COLMAP_DIR / 'aligned'
DATA_COLMAP_UNDISTORTED_DIR = DATA_COLMAP_DIR / 'undistorted'

DATA_OPENMVS_DIR = DATA_DIR / 'openmvs'
DATA_OPENMVS_ALIGNED_MVS = DATA_OPENMVS_DIR / 'aligned.mvs'
DATA_OPENMVS_DENSE_MVS = DATA_OPENMVS_DIR / 'dense.mvs'
DATA_OPENMVS_DENSE_PLY =  DATA_OPENMVS_DIR / 'dense.ply'
DATA_OPENMVS_MESH_MVS = DATA_OPENMVS_DIR / 'mesh.mvs'
DATA_OPENMVS_MESH_PLY =  DATA_OPENMVS_DIR / 'mesh.ply'
DATA_OPENMVS_REFINE_MVS = DATA_OPENMVS_DIR / 'refine.mvs'
DATA_OPENMVS_REFINE_PLY =  DATA_OPENMVS_DIR / 'refine.ply'
DATA_OPENMVS_TEXTURE_MVS = DATA_OPENMVS_DIR / 'texture.mvs'
DATA_OPENMVS_TEXTURE_PLY = DATA_OPENMVS_DIR / 'texture.ply'
DATA_OPENMVS_TEXTURE_OBJ = DATA_OPENMVS_DIR / 'texture.obj'

DATA_OPEN3D_DIR = DATA_DIR / 'open3d'
DATA_OPEN3D_MODEL_PLY = DATA_OPEN3D_DIR / 'model.ply'
DATA_OPEN3D_MODEL_OBJ = DATA_OPEN3D_DIR / 'model.obj'

# EXTENSIONS

SUPPORTED_INPUT_FORMATS = ('.jpg', '.jpeg', '.png', '.tiff', '.tif')
DEFAULT_PROCESSED_OUTPUT_FORMAT = '.png'
SUPPORTED_3D_FORMATS = ('.ply', '.obj', '.stl')
SUPPORTED_VIDEO_FORMATS = ('.mp4', '.mov', '.avi', '.mkv', '.webm', '.MOV', '.MP4')

# FLAGS

DEFAULT_SCAN_MODE: Literal['indoor', 'outdoor'] = 'indoor' 
DEFAULT_ENVIRONMENT_MODE: Literal['standard', 'underwater'] = 'underwater'
DEFAULT_IMAGES_EXTRACTION_MODE: Literal['video', 'images'] = 'video'
DEFAULT_MIN_PHOTO_ERROR = 5
DEFAULT_MIN_PHOTO_WARNING = 15

# VIDEO PARAMS

VIDEO_MIN_SHARPNESS = 30.0       # nitidezza per tenere il frame, più alta più è selettivo
VIDEO_MIN_DIFFERENCE = 0.25      # diversificazione delle foto
VIDEO_SAMPLE_INTERVAL = 0.5      # ogni quanto prende il frame

# VIDEO_MIN_SHARPNESS = 15.0       # nitidezza per tenere il frame, più alta più è selettivo
# VIDEO_MIN_DIFFERENCE = 0.10      # diversificazione delle foto
# VIDEO_SAMPLE_INTERVAL = 0.2      # ogni quanto prende il frame

# ENVIRONMENT SETUP
if DEFAULT_IMAGES_EXTRACTION_MODE == 'images':
    DEFAULT_ENVIRONMENT_CLEAN_UP = [DATA_PROCESSING_INTERIM_DIR, DATA_PROCESSING_PROCESSED_DIR, DATA_COLMAP_DIR, DATA_OPEN3D_DIR, DATA_OPENMVS_DIR]
elif DEFAULT_IMAGES_EXTRACTION_MODE == 'video':
    DEFAULT_ENVIRONMENT_CLEAN_UP = [DATA_PROCESSING_INTERIM_DIR, DATA_PROCESSING_PROCESSED_DIR, DATA_COLMAP_DIR, DATA_OPEN3D_DIR, DATA_OPENMVS_DIR, DATA_PROCESSING_RAW_DIR]



