from pathlib import Path

# NUOVA ORGANIZZAZIONE

# PER ORA CONSIDERO PROCESSING_INPUT_DIR COME INPUT E OPEN3D COME OUTPUT

BASE_DIR = Path(__file__).resolve().parent

ENGINES_DIR = BASE_DIR / 'engines'

# SRC ORGANIZATION

SRC_DIR = BASE_DIR / 'src'

SRC_PROCESSING_DIR = SRC_DIR / 'processing'
SRC_COLMAP_DIR = SRC_DIR / 'colmap'
SRC_OPENMVS_DIR = SRC_DIR / 'openmvs'
SRC_OPEN3D_DIR = SRC_DIR / 'open3d'

SRC_MODELS_DIR = SRC_DIR / 'models'
SRC_UTILS_DIR = SRC_DIR / 'utils'
SRC_CORE_DIR = SRC_DIR / 'core'

# DATA ORGANIZATION

DATA_DIR = BASE_DIR / 'data'

DATA_PROCESSING_DIR = DATA_DIR / 'processing'
DATA_PROCESSING_RAW_DIR = DATA_PROCESSING_DIR / 'raw'
DATA_PROCESSING_INTERIM_DIR = DATA_PROCESSING_DIR / 'interim'
DATA_PROCESSING_PROCESSED_DIR = DATA_PROCESSING_DIR / 'processed'

DATA_COLMAP_DIR = DATA_DIR / 'colmap'
DATA_COLMAP_DEFAULT_EXE = ENGINES_DIR / 'colmap/bin/colmap.exe'
DATA_COLMAP_DEFAULT_CAMERAS_DATABASE = DATA_COLMAP_DIR / 'cameras_data.db'
DATA_COLMAP_DEFAULT_GPS_DATA = DATA_COLMAP_DIR / 'gps_data.txt'
DATA_COLMAP_SPARSE_DIR = DATA_COLMAP_DIR / 'sparse'
DATA_COLMAP_ALIGNED_DIR = DATA_COLMAP_DIR / 'aligned'
DATA_COLMAP_UNDISTORTED_DIR = DATA_COLMAP_DIR / 'undistorted'

DATA_OPENMVS_DIR = DATA_DIR / 'openmvs'
DATA_OPENMVS_DENSE_DEFAULT_EXE = ENGINES_DIR / 'openmvs/DensifyPointCloud.exe'
DATA_OPENMVS_MESH_RECONSTRUCTOR_DEFAULT_EXE = ENGINES_DIR / 'openmvs/ReconstructMesh.exe'
DATA_OPENMVS_MESH_TEXTURIZER_DEFAULT_EXE = ENGINES_DIR / 'openmvs/TextureMesh.exe'
DATA_OPENMVS_INTERFACE_EXE = ENGINES_DIR / 'openmvs/InterfaceCOLMAP.exe'
DATA_OPENMVS_DEFAULT_MODEL = DATA_OPENMVS_DIR / 'model.mvs'
DATA_OPENMVS_DEFAULT_MODEL_DENSE_MVS = DATA_OPENMVS_DIR / 'model_dense.mvs'
DATA_OPENMVS_DEFAULT_MODEL_DENSE_PLY =  DATA_OPENMVS_DIR / 'model_dense.ply'
DATA_OPENMVS_DEFAULT_MODEL_MESH_MVS = DATA_OPENMVS_DIR / 'model_mesh.mvs'
DATA_OPENMVS_DEFAULT_MODEL_MESH_PLY = DATA_OPENMVS_DIR / 'model_mesh.ply'
DATA_OPENMVS_DEFAULT_MODEL_TEXTURED = DATA_OPENMVS_DIR / 'model_textured.obj'

DATA_OPEN3D_DIR = DATA_DIR / 'open3d'
DATA_OPEN3D_MESH_MODEL = DATA_OPEN3D_DIR / 'model.ply'
DATA_OPEN3D_EXPORTED_MODEL = DATA_OPEN3D_DIR / 'model.obj'

# ENVIRONMENT SETUP

DEFAULT_ENVIRONMENT_CLEAN_UP = [DATA_PROCESSING_INTERIM_DIR, DATA_PROCESSING_PROCESSED_DIR, DATA_COLMAP_DIR, DATA_OPEN3D_DIR, DATA_OPENMVS_DIR]

# EXTENSIONS

SUPPORTED_INPUT_FORMATS = ('.jpg', '.jpeg', '.png', '.tiff', '.tif')
DEFAULT_PROCESSED_OUTPUT_FORMAT = '.png'
SUPPORTED_3D_FORMATS = ('.ply', '.obj', '.stl')

# FLAGS

DEFAULT_SCAN_MODE = 'indoor' # 'indoor' | 'outdoor' 
DEFAULT_ENVIRONMENT_MODE = 'standard' # 'standard' | 'underwater'
DEFAULT_MIN_PHOTO_ERROR = 5
DEFAULT_MIN_PHOTO_WARNING = 15


